# Generated by Django 5.0.3 on 2024-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_carttable"),
    ]

    operations = [
        migrations.AddField(
            model_name="carttable",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
