# Generated by Django 4.0.3 on 2024-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_carttable_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='price',
            field=models.IntegerField(),
        ),
    ]
